export const TITLE = 'TITLE'
export const TEXT_BOX = 'TEXT_BOX'
export const SLOGAN = 'SLOGAN'
export const AUDIO = 'AUDIO'
export const BLANK = 'BLANK'
export const COLOPHON = 'COLOPHON'
export const TITLE_LEFT = 'TITLE_LEFT'
export const CAPTION = 'CAPTION'
